apiVersion: v1
kind: Service
metadata:
  name: shopcrm-front-prod-service
  namespace: 'ENVIRONMENT'
spec:
  type: NodePort
  selector:
    app: shopcrm-front-prod
  ports:
    - protocol: TCP
      port: 'POD_PORT'
      targetPort: 'POD_PORT'
      nodePort: 'NODE_PORT'
